version: 1.0.{build}
clone_folder: C:\projects\kevinphelps\csharp-string-interpolator
clone_script:
- git clone -q --depth=1 https://github.com/vintage-software/vstack.git C:\projects\vintage-software\vstack
- git clone -q --depth=1 https://github.com/vintage-software/vstack-common.git C:\projects\vintage-software\vstack-common
- git clone -q --depth=50 --branch=%APPVEYOR_REPO_BRANCH% https://github.com/kevinphelps/csharp-string-interpolator.git C:\projects\kevinphelps\csharp-string-interpolator
before_build:
- git reset --hard %APPVEYOR_REPO_COMMIT%
- nuget restore C:\projects\vintage-software\vstack-common\Vstack.Common.sln
- nuget restore C:\projects\kevinphelps\csharp-string-interpolator\StringInterpolator.sln
build:
  verbosity: minimal
configuration: Release